### ISSUE TITLE
Complete Extra Credit 

### ISSUE THREAD

**Issue by ragmha** [ragmha/fm-JS101#1]
**TODO** 🎉  🎉  🎉
## CALLBACKS
- [ ] [Callbacks](https://github.com/ragmha/fm-JS101/blob/master/challenges/Callbacks/exercise/README.md) **Question 4** 🎉 

- [ ] [Callbacks + Underscore](https://github.com/ragmha/fm-JS101/blob/master/challenges/Callbacks/exercise/README-2.md) **All**  🎉

## CLOSURE
- [ ] [Closure](https://github.com/ragmha/fm-JS101/blob/master/challenges/Closures/exercise/README.md) **Question 8-10** 🎉
